# Generated by Django 5.1.3 on 2024-12-02 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainerapp', '0003_marks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcourse',
            old_name='student',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='student',
            new_name='employee',
        ),
    ]
